# !!! This compose file only for development use
version: '3.8'
services:
  backend:
    build: ./packages/backend
    working_dir: /app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
  frontend:
    build: ./packages/frontend
    working_dir: /app
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'notebook'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'alice'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Alice456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql     
volumes:
  my-db:



